db_shenanigans/DB/urls.py
from django.urls import path
from . import views

app_name = 'DB'
urlpatterns = [
    path('', views.info, name='info'),
    path('config', views.index, name='index'),
    path('add', views.add, name='add'),
    path('add_firm', views.add_firm, name='add_firm'),
    path('add_ware', views.add_ware, name='add_ware')
]

db_shenanigans/db_shenanigans/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('DB.urls')),
    path('logging/', include('django.contrib.auth.urls'))
]

db_shenanigans/DB/models.py
from django.db import models


class Firm(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(unique=True, max_length=200)
    address = models.CharField(max_length=200)
    phone_number = models.IntegerField()

    def __str__(self):
        return str(self.name)


class Ware(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(unique=True, max_length=100)
    price = models.FloatField()
    firm_id = models.ForeignKey(Firm, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.name)


class Customer(models.Model):
    id = models.AutoField(primary_key=True)
    full_name = models.CharField(max_length=100)
    email = models.CharField(max_length=100, null=True)
    phone_number = models.IntegerField(null=True)

    def __str__(self):
        return str(self.full_name)


class ConsignmentNote(models.Model):
    id = models.AutoField(primary_key=True)
    customer_id = models.ForeignKey(Customer, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.id) + ', ' + str(self.customer_id)


class Log(models.Model):
    id = models.AutoField(primary_key=True)
    date = models.DateTimeField()
    ware_quantity = models.IntegerField()
    ware_id = models.ForeignKey(Ware, on_delete=models.CASCADE)
    consignment_note_id = models.ForeignKey(ConsignmentNote, on_delete=models.CASCADE)

db_shenanigans/DB/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.core.serializers import serialize
from django.http import HttpRequest, JsonResponse, HttpResponse
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from .models import Customer, ConsignmentNote, Firm, Ware, Log
import json
import datetime


@login_required(login_url='/logging/login')
def index(request):

    context = {
        'customers': Customer.objects.all(),
        'notes': ConsignmentNote.objects.all(),
        'firms': Firm.objects.all(),
        'wares': Ware.objects.all(),
        'logs': Log.objects.all(),
        'max': range(max([Customer.objects.count(), Customer.objects.count(),
                     Customer.objects.count(), Customer.objects.count(), Customer.objects.count()])),
        'user': request.user
    }

    if request.method == 'GET':
        if request.GET.get('default'):
            context['default'] = request.GET.get('default')
        else:
            context['default'] = 'ware'
        return render(request, 'DB/index.html', context)

    if request.method == 'DELETE':
        data = request.body.decode()
        data = json.loads(data)

        entity = globals()[data['table'].capitalize()]
        obj = entity.objects.get(id=data['id'])

        obj.delete()
        return HttpResponse()

    if request.method == 'PUT':
        data = request.body.decode()
        data = json.loads(data)

        entity = globals()[data['table'].capitalize()]
        obj = entity.objects.get(id=data['id'])

        for key in data:
            if key not in ['table', 'id']:
                print(data[key])
                if data[key] != getattr(obj, key):
                    setattr(obj, key, data[key])

        obj.save()
        return HttpResponse()


@login_required(login_url='/logging/login')
def add(request: HttpRequest):
    context = {
        'customer_list': Customer.objects.all(),
        'ware_list': Ware.objects.all(),
        'user': request.user
    }
    if request.method == 'GET':
        return render(request, 'DB/add.html', context)

    if request.method == 'POST':
        context['chosen_wares'] = []
        context['unfilled_wares'] = []
        for key in request.POST:
            if key.startswith('ware'):
                q_key = 'quantity' + str(key[4:])
                context['chosen_wares'].append((request.POST[key], request.POST[q_key]))
            elif key.startswith('quantity'):
                continue
            else:
                context[key] = request.POST[key]

        if request.POST['flag'] == 'e':
            if not request.POST['existing']:
                context['existing_error'] = True
                return render(request, 'DB/add.html', context)
            customer = request.POST['existing'].split(', ')

            if customer[1].isdecimal():
                db_customer = Customer.objects.get(full_name=customer[0], phone_number=int(customer[1]))
            else:
                db_customer = Customer.objects.get(full_name=customer[0], email=customer[1])
        else:
            if not request.POST['email'] and not request.POST['phone'] or not request.POST['name']:
                if not request.POST['name']:
                    context['name_error'] = True
                if not request.POST['email'] and not request.POST['phone']:
                    context['email_phone_error'] = True
                return render(request, 'DB/add.html', context)

            query = Customer.objects.filter(full_name=request.POST['name'])

            if request.POST['email']:
                query.filter(email=request.POST['email'])

            if request.POST['phone']:
                query.filter(phone_number=request.POST['phone'])

            if len(query) > 0:
                context['already_exists'] = True
                return render(request, 'DB/add.html', context)

            db_customer = Customer(full_name=request.POST['name'])
            db_customer.phone_number = request.POST['phone'] if request.POST['phone'].isdecimal() else None
            db_customer.email = request.POST['email'] if request.POST['email'] else None
            db_customer.save()

        c = ConsignmentNote(customer_id=db_customer)

        error = False
        for i in range(len(context['chosen_wares'])):
            if not context['chosen_wares'][i][0] or not context['chosen_wares'][i][1]:
                context['unfilled_wares'].append(i)
                error = True

        if error:
            return render(request, 'DB/add.html', context)

        c.save()

        for w_q in context['chosen_wares']:
            log = Log(consignment_note_id=c, ware_id=Ware.objects.get(name=w_q[0]),
                      ware_quantity=w_q[1], date=datetime.datetime.now())
            log.save()

        return redirect('/config')


@login_required(login_url='/logging/login')
def add_firm(request):
    context = {'user': request.user}
    if request.method == 'GET':
        return render(request, 'DB/add_firm.html')

    if request.method == 'POST':
        if Firm.objects.filter(name=request.POST['name']):
            context['error'] = True
            return render(request, 'DB/add_firm.html', context)

        f = Firm(name=request.POST['name'], phone_number=request.POST['number'], address=request.POST['address'])

        f.save()
        return redirect('/config')


@login_required(login_url='/logging/login')
def add_ware(request):
    context = {'firms': Firm.objects.all(), 'user': request.user}
    if request.method == 'GET':
        return render(request, 'DB/add_ware.html', context)

    if request.method == 'POST':
        if Ware.objects.filter(name=request.POST['name']):
            context['error'] = True
            return render(request, 'DB/add_ware.html', context)

        w = Ware(name=request.POST['name'], price=request.POST['price'],
                 firm_id=Firm.objects.get(name=request.POST['manufacturer']))

        w.save()
        return redirect('/config')


def info(request):
    if request.method == 'GET':
        return render(request, 'DB/info.html')
    else:
        data = request.body.decode()
        data = json.loads(data)

        if data['type'] == 'Phone':
            if data['query'].isdecimal() and Customer.objects.filter(phone_number=data['query']):
                c = Customer.objects.get(phone_number=data['query'])
            else:
                return HttpResponse(json.dumps({'number_err': 'true'}))
        else:
            if Customer.objects.filter(email=data['query']):
                c = Customer.objects.get(email=data['query'])
            else:
                return HttpResponse(json.dumps({'email_err': 'true'}))

        notes = ConsignmentNote.objects.filter(customer_id=c.id)
        logs = []
        logs_to_json = []

        for note in notes:
            logs.extend(Log.objects.filter(consignment_note_id=note.id))

        for log in logs:
            logs_to_json.append({
                'date': log.date.date().isoformat(),
                'quantity': log.ware_quantity,
                'ware': log.ware_id.name,
                'price': log.ware_id.price * log.ware_quantity
            })

        data = json.dumps(logs_to_json)

        return HttpResponse(data)

db_shenanigans/DB/templates/DB/add.html
{% load static %}
<head xmlns="">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="{% static 'DB/chosen.jquery.js'%}"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'DB/styles/style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'DB/chosen.css' %}">
</head>
<body>
    <div class="sidebar">
        <div class="add_links">
            <img src="https://image.flaticon.com/icons/svg/25/25304.svg" id="add" class="side">
            <a href="{% url 'DB:add' %}" class="link">Add a note</a> <br>
            <a href="{% url 'DB:add_firm' %}" class="link">Add a firm</a> <br>
            <a href="{% url 'DB:add_ware' %}" class="link">Add a ware</a>
        </div>
        <div class="config_links">
            <img src="https://static.thenounproject.com/png/1241-200.png" id="config" class="side">
            <a href="{% url 'DB:index' %}" class="link">Configure</a>
        </div>
        <div class="info_links">
            <img src="https://cdn4.iconfinder.com/data/icons/defaulticon/icons/png/256x256/info.png" id="info" class="side">
            <a href="{% url 'DB:info' %}" class="link">Buying Info</a> <br>
            {% if user.is_authenticated %}
                <a href="{% url 'logout' %}" class="link">Logout</a>
            {% else %}
                <a href="{% url 'login' %}" class="link">Login</a>
            {% endif %}
        </div>
    </div>

<div class="main">
    <h1> New consignment note </h1> <br>

    {% if name_error or email_phone_error or already_exists or switch %}
        <label class="error_switch" style="display: none"></label>
    {% endif %}

    <form id="add" method="post" action="{% url 'DB:add' %}" style="margin-top: -20px">
        {% csrf_token %}
        <br><span>Pick a customer:</span> <br>
        <input class="flag" name="flag" type="text">
        {% if already_exists %}
            <h3 style="color: red">The customer already exists, use existing tab</h3>
        {% endif %}
        <div class="existing">
            <select name="existing" class="customer" data-placeholder="Select a customer..." tabindex="-1" >
                <option> </option>
                {% if customer_list %}
                    {% for customer in customer_list %}
                        {% if customer.phone_number %}
                            <option> {{ customer.full_name }}, {{ customer.phone_number }}</option>
                        {% else %}
                            <option>{{ customer.full_name }}, {{ customer.email }}</option>
                        {% endif %}
                    {% endfor %}
                {% endif %}
            </select>
            {% if existing_error %}
                <label style="color: red">* - please select a customer or create a new one</label>
            {% endif %}
            <br>
            <button type="button" id="new">New</button>
        </div>

        <div class="new">
            <label><b>NOTE:</b> while creating a new user, fill name and either email or phone (can be both)</label> <br> <br>
            <label for="name">Enter name: </label> <br>
            <input value="{{ name }}" name="name" type="text" title="Name" id="name">
            {% if name_error %}
                <label style="color: red"> * - please type customer's name</label>
            {% endif %}
            <br>
            {% if email_phone_error %}
                <label>Enter email: <br> </label><input value="{{ email }}" name="email" type="text" title="Email" id="email"><label style="color: red"> * - please fill this field</label> <br>
                <label>Enter phone number: <br> </label><input value="{{ phone }}" name="phone" type="text" title="phone_number" id="phone_num"><label style="color: red"> * - or this one</label> <br>
            {% else %}
                <label for="email">Enter email: </label> <br>
                <input value="{{ email }}" name="email" type="text" title="Email" id="email"> <br>
                <label for="phone_num">Enter phone number: </label> <br>
                <input value="{{ phone }}" name="phone" type="text" title="phone_number" id="phone_num"> <br>
            {% endif %}
            <button type="button" id="existing">Existing</button>
        </div>

        <br><span>Choose wares and their quantity:</span><br>
        <div class="placeholder">
        {% if chosen_wares %}
            {% for err_ware in chosen_wares %}
                <select name="ware_{{ forloop.counter }}" class="ware" data-placeholder="Select a ware..." tabindex="-1">
                    <option> </option>
                        {% if ware_list %}
                            {% for ware in ware_list %}
                                {% if ware.name == err_ware.0 %}
                                    <option selected="selected" > {{ ware.name }}</option>
                                {% else %}
                                    <option> {{ ware.name }}</option>
                                {% endif %}
                            {% endfor %}
                        {% endif %}
                    </select>
                <input value="{{ err_ware.1 }}" name="quantity_{{ forloop.counter }}" type="text" class="priceBox" style="width: 50px">
                {% if forloop.counter0 in unfilled_wares %}
                    <label style="color: red">* - please fill both fields</label>
                {% endif %}
                <br>
            {% endfor %}
        {% else %}
            <select name="ware_1" class="ware" data-placeholder="Select a ware..." tabindex="-1">
                    <option> </option>
                        {% if ware_list %}
                            {% for ware in ware_list %}
                                <option> {{ ware.name }}</option>
                            {% endfor %}
                        {% endif %}
                    </select>
                <input name="quantity_1" type="text" class="priceBox" style="width: 50px"><br>
        {% endif %}
        </div>

        <button type="button" id="plus">+</button>
        <button type="button" id="minus">-</button>
        <br>
        <br>
        <br>
        <br>
        <button type="submit" id="submit">Add</button>
    </form>
</div>
</body>

<script>
    $(document).ready(function () {
        $('.customer').chosen();
        $('.ware').chosen();
        $('.priceBox').forceNumeric();
        $('#phone_num').forceNumeric();
        $('.flag').hide();
        if ($('.error_switch').length) {
            $('.existing').hide();
            $('.flag').val('n');
        } else {
            $('.new').hide();
            $('.flag').val('e');
        }
    });

    $('#plus').click(function () {
        $('.ware').last().clone().appendTo('.placeholder');
        $('.ware').last().css('display', 'block');
        $('.ware').last().attr('name', 'ware_' + $('.ware').length);
        $('.ware').last().children().removeAttr('selected')
        $('.ware').last().chosen();
        $('.chosen-container').last().css('display', 'inline-block');
        $('.priceBox').last().clone().appendTo('.placeholder');
        $('.priceBox').last().forceNumeric();
        $('.priceBox').last().css('margin-left', '5px');
        $('.priceBox').last().val('');
        $('.priceBox').last().attr('name', 'quantity_' + $('.priceBox').length);
        $('.placeholder').append('<br class="br">');
    });

    $('#minus').click(function () {
        if ($('.ware').length > 1) {
            $('.ware').last().remove();
            $('.chosen-container').last().remove();
            $('.priceBox').last().remove();
            $('.br').last().remove();
        }
    });

    $('#new').click(function () {
        $('.existing').hide();
        $('.new').show();
        $('.flag').val('n');
    });

    $('#existing').click(function () {
        $('.new').hide();
        $('#name').val('');
        $('#email').val('');
        $('#phone_num').val('');
        $('.existing').show();
        $('.flag').val('e');
    });

    jQuery.fn.forceNumeric = function () {
         return this.each(function () {
             $(this).keydown(function (e) {
                 let key = e.which || e.keyCode;

                 if (!e.shiftKey && !e.altKey && !e.ctrlKey &&
                     key >= 48 && key <= 57 ||
                     key >= 96 && key <= 105 ||
                    key == 190 || key == 188 || key == 109 || key == 110 ||
                    key == 8 || key == 9 || key == 13 ||
                    key == 35 || key == 36 ||
                    key == 37 || key == 39 ||
                    key == 46 || key == 45)
                     return true;

                 return false;
             });
         });
    }
</script>

db_shenanigans/DB/templates/DB/add_firm.html
{% load static %}
<head xmlns="">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'DB/styles/style.css' %}">

<body>
    <div class="sidebar">
        <div class="add_links">
            <img src="https://image.flaticon.com/icons/svg/25/25304.svg" id="add" class="side">
            <a href="{% url 'DB:add' %}" class="link">Add a note</a> <br>
            <a href="{% url 'DB:add_firm' %}" class="link">Add a firm</a> <br>
            <a href="{% url 'DB:add_ware' %}" class="link">Add a ware</a>
        </div>
        <div class="config_links">
            <img src="https://static.thenounproject.com/png/1241-200.png" id="config" class="side">
            <a href="{% url 'DB:index' %}" class="link">Configure</a>
        </div>
        <div class="info_links">
            <img src="https://cdn4.iconfinder.com/data/icons/defaulticon/icons/png/256x256/info.png" id="info" class="side">
            <a href="{% url 'DB:info' %}" class="link">Buying Info</a> <br>
            {% if user.is_authenticated %}
                <a href="{% url 'logout' %}" class="link">Logout</a>
            {% else %}
                <a href="{% url 'login' %}" class="link">Login</a>
            {% endif %}
        </div>
    </div>

    <div class="main">
        <h1>Add a firm</h1> <br>
        {% if error %}
            <h3 style="color: red; margin-top: 0px; padding-top: 0px">* A firm with this name already exists</h3>
        {% endif %}
        <form id="addFirm" method="post" action="{% url 'DB:add_firm' %}">
        {% csrf_token %}
            <label id="name_err" for="name">Enter a name: <br><input id="name" name="name" ></label><br>
            <label id="number_err" for="number">Enter a number: <br><input id="number" name="number" ></label><br>
            <label id="address_err" for="address">Enter an address: <br><input id="address" name="address"></label><br>
        <button type="submit">Add</button>
        </form>
    </div>
</body>

<script>
    $(document).ready(function () {
        $('#number').forceNumeric();
    });

    $('#addFirm').submit(function (e) {
        $('.kill').each(function () {
            $(this).remove();
        });
        if ($('#name').val() === '') {
            $('#name_err').append('<label class="kill" style="color:red"> * - please fill</label>');
            e.preventDefault();
        }
        if ($('#number').val() === '') {
            $('#number_err').append('<label class="kill" style="color:red"> * - please fill</label>');
            e.preventDefault();
        }
        if ($('#address').val() === '') {
            $('#address_err').append('<label class="kill" style="color:red"> * - please fill</label>');
            e.preventDefault();
        }
    });

    jQuery.fn.forceNumeric = function () {
         return this.each(function () {
             $(this).keydown(function (e) {
                 let key = e.which || e.keyCode;

                 if (!e.shiftKey && !e.altKey && !e.ctrlKey &&
                     key >= 48 && key <= 57 ||
                     key >= 96 && key <= 105 ||
                    key == 190 || key == 188 || key == 109 || key == 110 ||
                    key == 8 || key == 9 || key == 13 ||
                    key == 35 || key == 36 ||
                    key == 37 || key == 39 ||
                    key == 46 || key == 45)
                     return true;

                 return false;
             });
         });
    }
</script>

db_shenanigans/DB/templates/DB/add_ware.html
{% load static %}
<head xmlns="">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="{% static 'DB/chosen.jquery.js'%}"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'DB/styles/style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'DB/chosen.css' %}">
</head>

<body>
    <div class="sidebar">
        <div class="add_links">
            <img src="https://image.flaticon.com/icons/svg/25/25304.svg" id="add" class="side">
            <a href="{% url 'DB:add' %}" class="link">Add a note</a> <br>
            <a href="{% url 'DB:add_firm' %}" class="link">Add a firm</a> <br>
            <a href="{% url 'DB:add_ware' %}" class="link">Add a ware</a>
        </div>
        <div class="config_links">
            <img src="https://static.thenounproject.com/png/1241-200.png" id="config" class="side">
            <a href="{% url 'DB:index' %}" class="link">Configure</a>
        </div>
        <div class="info_links">
            <img src="https://cdn4.iconfinder.com/data/icons/defaulticon/icons/png/256x256/info.png" id="info" class="side">
            <a href="{% url 'DB:info' %}" class="link">Buying Info</a> <br>
            {% if user.is_authenticated %}
                <a href="{% url 'logout' %}" class="link">Logout</a>
            {% else %}
                <a href="{% url 'login' %}" class="link">Login</a>
            {% endif %}
        </div>
    </div>

    <div class="main">
        <h1>Add a ware</h1><br>
        {% if error %}
            <h3 style="color: red; margin-top: 0px; padding-top: 0px">* A ware with this name already exists</h3>
        {% endif %}
        <form id="addWare" method="post" action="{% url 'DB:add_ware' %}">
        {% csrf_token %}
            <label id="err_name" for="name">Enter a name: <br> <input id="name" name="name"></label><br>
            <label id="err_price" for="price">Enter a price: <br><input id="price" name="price"></label><br>
            <div id="error">
                <select id="firm" name="manufacturer" data-placeholder="Select a firm...">
                    <option></option>
                    {% for firm in firms %}
                        <option>{{ firm.name }}</option>
                    {% endfor %}
                </select>
            </div>
        <button type="submit">Add</button>
        </form>
    </div>
</body>

<script>
    $(document).ready(function () {
        $('#firm').chosen();
        $('#price').forceNumeric();
    });

    $('#addWare').submit(function (e) {
        $('.kill').each(function () {
            $(this).remove();
        });
        if ($('#name').val() === '') {
            $('#err_name').append('<label class="kill" style="color:red"> * - please fill</label>');
            e.preventDefault();
        }
        if ($('#price').val() === '') {
            $('#err_price').append('<label class="kill" style="color:red"> * - please fill</label>');
            e.preventDefault();
        }
        if ($('#firm option:selected').text() === '') {
            $('#error').append('<label class="kill" style="color:red"> * - please fill</label>');
            e.preventDefault();
        }
    });

    jQuery.fn.forceNumeric = function () {
         return this.each(function () {
             $(this).keydown(function (e) {
                 let key = e.which || e.keyCode;

                 if (!e.shiftKey && !e.altKey && !e.ctrlKey &&
                     key >= 48 && key <= 57 ||
                     key >= 96 && key <= 105 ||
                    key == 190 || key == 188 || key == 109 || key == 110 ||
                    key == 8 || key == 9 || key == 13 ||
                    key == 35 || key == 36 ||
                    key == 37 || key == 39 ||
                    key == 46 || key == 45)
                     return true;

                 return false;
             });
         });
    }
</script>

db_shenanigans/DB/templates/DB/info.html
<!DOCTYPE html>
<html lang="en">

{% load static %}

<head>
    <meta charset="UTF-8">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="{% static 'DB/chosen.jquery.js'%}"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'DB/styles/style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'DB/chosen.css' %}">
    <title>Find buying history</title>
</head>
<body>
    <div class="sidebar">
        <div class="add_links">
            <img src="https://image.flaticon.com/icons/svg/25/25304.svg" id="add" class="side">
            <a href="{% url 'DB:add' %}" class="link">Add a note</a> <br>
            <a href="{% url 'DB:add_firm' %}" class="link">Add a firm</a> <br>
            <a href="{% url 'DB:add_ware' %}" class="link">Add a ware</a>
        </div>
        <div class="config_links">
            <img src="https://static.thenounproject.com/png/1241-200.png" id="config" class="side">
            <a href="{% url 'DB:index' %}" class="link">Configure</a>
        </div>
        <div class="info_links">
            <img src="https://cdn4.iconfinder.com/data/icons/defaulticon/icons/png/256x256/info.png" id="info" class="side">
            <a href="{% url 'DB:info' %}" class="link">Buying Info</a> <br>
            {% if user.is_authenticated %}
                <a href="{% url 'logout' %}" class="link">Logout</a>
            {% else %}
                <a href="{% url 'login' %}" class="link">Login</a>
            {% endif %}
        </div>
    </div>
    <div class="main">
        <h2>Find your note</h2><br>
        <span> Here you can find items you bought either by email or by phone number </span><br><br>

        <div id="error_placeholder"></div><br>

        <input id="search_input">

        <select tabindex="2" id="selector">
            <option>Email</option>
            <option>Phone</option>
        </select>

        <button id="search">Search</button> <br> <br>

        <div id="placeholder"></div>
    </div>

    <div class="misc" style="display: none">
        <label id="token">{% csrf_token %}</label>
        <label id="lnk">{% url 'DB:info' %}</label>
    </div>
</body>

<script>
    $('#search').click(function () {
        let data = {
            "query": $('#search_input').val(),
            "type": $('#selector option:selected').text()
        };
        console.log(data);
        $.ajax({
            url: $('#lnk').val(),
            method: 'POST',
            data: JSON.stringify(data),
            beforeSend: function(xhr) {
                xhr.setRequestHeader("X-CSRFToken", $('[name=csrfmiddlewaretoken]').val());
            },
            success: function (data) {
                data = JSON.parse(data);
                if ('email_err' in data === true) {
                    $('#error_placeholder').empty();
                    $('#error_placeholder').append("<span style='color: red'>There's no customer with this email</span>");
                    return;
                }

                if ('number_err' in data === true) {
                    $('#error_placeholder').empty();
                    $('#error_placeholder').append("<span style='color: red'>There's no customer with this phone number</span>");
                    return;
                }
                let placeHolder = $('#placeholder');
                placeHolder.empty();
                let appendStr = "<table id='result'><th>Ware</th><th>Quantity</th><th>Total</th><th>Date</th>";
                for (let i = 0; i < data.length; i++){
                    appendStr += "<tr>";
                    appendStr += "<td>" + data[i]["ware"] + "</td>";
                    appendStr += "<td>" + data[i]["quantity"] + "</td>";
                    appendStr += "<td>" + data[i]["price"] + "</td>";
                    appendStr += "<td>" + data[i]["date"] + "</td></tr>";
                }
                appendStr += "</table>";
                placeHolder.append(appendStr);
                placeHolder.css('display', 'block');
            }
        });
    });
</script>
</html>

db_shenanigans/DB/templates/DB/success.html
{% load static %}

<h1> Successful </h1>
<a href="{% url 'DB:index' %}">back to main</a>